name       : libhunspell
version    : 1.6.2
release    : 3
source     :
    - https://github.com/hunspell/hunspell/archive/v1.6.2.tar.gz : 3cd9ceb062fe5814f668e4f22b2fa6e3ba0b339b921739541ce180cac4d6f4c4
homepage   : https://hunspell.github.io/
license    :
    - MPL-1.1
    - GPL-2.0
    - LGPL-2.1
component  : office
summary    : Hunspell spelling checker
description: |
    Hunspell is a spell checker and morphological analyzer library
    and program designed for languages with rich morphology and complex
    word compounding or character encoding.
setup      : |
    %reconfigure --disable-static \
                 --with-ui \
                 --with-readline
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
