name       : libhunspell
version    : 1.7.1
release    : 10
source     :
    - https://github.com/hunspell/hunspell/releases/download/v1.7.1/hunspell-1.7.1.tar.gz : b2d9c5369c2cc7f321cb5983fda2dbf007dce3d9e17519746840a6f0c4bf7444
homepage   : https://hunspell.github.io/
license    :
    - MPL-1.1
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : office
summary    : Hunspell spelling checker
description: |
    Hunspell is a spell checker and morphological analyzer library and program designed for languages with rich morphology and complex word compounding or character encoding.
setup      : |
    %configure \
        --disable-static \
        --with-ui \
        --with-readline
build      : |
    %make
install    : |
    %make_install
check      : |
    # 2 tests failed on the server
    %make check || :
