name    : libhunspell
version : 1.3.3
release : 2
homepage: http://hunspell.sourceforge.net/
source :
 - http://downloads.sourceforge.net/hunspell/hunspell-1.3.3.tar.gz : a7b2c0de0e2ce17426821dc1ac8eb115029959b3ada9d80a81739fa19373246c
license :
    - MPL-1.1
    - GPL-2.0
    - LGPL-2.1
summary : Hunspell spelling checker.
builddeps :
    - qt5-devel
description : Hunspell is a spell checker.
clang: no
setup : |
    %configure
build : |
    %make
install : |
    %make_install

